version: "3.8"

services:
  67c1c53dc19fddbe9f8f4504_service:
    build: .
    container_name: 67c1c53dc19fddbe9f8f4504_container
    # Adjust your desired external port mapping here. For example:
    # "8502:8501" means the app is internally on 8501, but externally accessible on 8502.
    ports:
      - "8518:8501"
    environment:
      - PORT=8501  # This must match the internal port used by Streamlit
    restart: always
